# Generated by Django 2.2.4 on 2020-12-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(default=' test test', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quoted_by', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(default=' test test', on_delete=django.db.models.deletion.CASCADE, related_name='quotes_posted', to='test_app.User')),
                ('favouriting_users', models.ManyToManyField(related_name='favourite_quotes', to='test_app.User')),
            ],
        ),
    ]
